import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  fullScreenCamera: {
    ...StyleSheet.absoluteFillObject,
  },
  snapFlash: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#ffffff',
    zIndex: 99,
  },
  cameraTintLight: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  overlaySafeArea: {
    flex: 1,
    justifyContent: 'space-between',
  },
  newHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 80,
    position: 'relative',
  },
  headerLeft: {
    position: 'absolute',
    left: 16,
    top: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  marginLeft10: {
    marginLeft: 10,
  },
  headerSyncBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#F27121',
    borderWidth: 1,
    borderColor: '#fff',
  },
  headerCenter: {
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 12,
  },
  topTime: {
    color: '#fff',
    fontSize: 30,
    fontWeight: '900',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  topDate: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 15,
    fontWeight: '600',
    marginTop: -2,
  },
  headerRight: {
    position: 'absolute',
    right: 16,
    top: 0,
    bottom: 0,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  miniOfflineBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  miniOfflineBadgeActive: {
    borderColor: '#F27121',
    backgroundColor: 'rgba(242,113,33,0.2)',
  },
  miniOfflineText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    marginLeft: 4,
  },
  portraitProfileBar: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  portraitProfileImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#fff',
  },
  portraitProfilePlaceholder: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  portraitProfileInfo: {
    marginLeft: 12,
    marginRight: 12,
    flex: 1,
  },
  portraitProfileName: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  portraitProfileRole: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    fontWeight: '600',
  },
  clockInTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.2)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginTop: 10,
  },
  clockInTimeText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 8,
  },
  clockInTimeTextMini: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 8,
  },
  faceScannerArea: { alignItems: 'center' },
  faceScannerAreaRight: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingBottom: 60,
  },
  faceFrame: {
    width: 240,
    height: 240,
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 20,
    overflow: 'visible',
    position: 'relative',
  },
  corner: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderColor: '#F27121',
  },
  cornerTopLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 5,
    borderLeftWidth: 5,
    borderTopLeftRadius: 15,
  },
  cornerTopRight: {
    top: 0,
    right: 0,
    borderTopWidth: 5,
    borderRightWidth: 5,
    borderTopRightRadius: 15,
  },
  cornerBottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 5,
    borderLeftWidth: 5,
    borderBottomLeftRadius: 15,
  },
  cornerBottomRight: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    borderBottomRightRadius: 15,
  },
  scanLine: {
    width: '100%',
    height: 4,
    backgroundColor: '#F27121',
    shadowColor: '#F27121',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 10,
    zIndex: 10,
  },
  successIconWrap: {
    position: 'absolute',
    top: 58,
    zIndex: 12,
  },
  faceIconBackground: {
    position: 'absolute',
    top: 60,
  },
  countdownText: {
    position: 'absolute',
    top: 40,
    fontSize: 100,
    fontWeight: '900',
    color: '#F27121',
    textShadowColor: 'rgba(0,0,0,0.6)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  scanInstructionText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 1,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  scanInstructionTextRight: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  faceHintText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  faceHintTextRight: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 12,
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  scannerOverlayContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  portraitFaceContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  portraitFooter: {
    paddingHorizontal: 20,
    paddingBottom: 25,
    alignItems: 'center',
  },
  verifyingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#F27121',
  },
  verifyingPillText: {
    color: '#fff',
    marginLeft: 8,
    fontWeight: '700',
  },
  footerButtons: {
    flexDirection: 'row',
    width: '100%',
    gap: 12,
  },
  mainActionButton: {
    flex: 1,
    height: 60,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  mainActionButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '900',
  },
  splitScreenContainer: {
    flex: 1,
    flexDirection: 'row-reverse',
  },
  employeeDetailPanel: {
    flex: 4,
    zIndex: 10,
    overflow: 'hidden',
  },
  cameraPanel: {
    flex: 6,
    backgroundColor: '#000',
  },
  panelSafeArea: {
    flex: 1,
    justifyContent: 'space-between',
  },
  cameraSafeArea: {
    flex: 1,
    justifyContent: 'space-between',
  },
  employeeDetailPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 20,
    paddingLeft: 20,
    paddingRight: 20,
  },
  headerIconButtonLight: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  profileInfoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  profileImageContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  profileImage: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 5,
    borderColor: '#fff',
  },
  profileImagePlaceholder: {
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 5,
    borderColor: '#fff',
  },
  profileName: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 5,
    textShadowColor: 'rgba(0,0,0,0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  profileRole: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 2,
  },
  profileDept: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 20,
  },
  employeeDetailPanelFooter: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 20,
    width: '100%',
    marginTop: 20,
  },
  mainActionButtonLeft: {
    width: '100%',
    paddingVertical: 20,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  mainActionButtonTextLeft: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 1,
  },
  verifyingPillLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
  },
  verifyingPillTextLeft: {
    fontSize: 16,
    fontWeight: '800',
    marginLeft: 10,
  },
  cameraPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 20,
  },
  headerCenterRight: {
    alignItems: 'flex-start',
  },
  topTimeRight: {
    color: '#fff',
    fontSize: 36,
    fontWeight: '900',
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  topDateRight: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 18,
    fontWeight: '700',
    marginTop: -4,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  fullScreenDetectionOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 80,
    elevation: 80,
  },
  detectionFaceBox: {
    position: 'absolute',
    left: 37,
    top: 20,
    width: 165,
    height: 200,
    borderRadius: 0,
    borderWidth: 1.0,
    borderColor: '#ffffff',
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    zIndex: 2,
    elevation: 2,
  },
  bystanderFaceBox: {
    position: 'absolute',
    borderColor: 'rgba(91, 91, 91, 0.89)',
    borderStyle: 'dashed',
    borderWidth: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  detectionFaceBoxActive: {
    borderColor: '#4ade80',
    backgroundColor: 'transparent',
  },
  detectionStatusCard: {
    position: 'absolute',
    top: 12,
    left: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    minWidth: 128,
    zIndex: 3,
    elevation: 3,
  },
  detectionStatusText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
    lineHeight: 16,
  },
  mainActionButtonClockOut: {
    backgroundColor: '#C0392B',
  },
  mainActionButtonLeftClockOut: {
    backgroundColor: '#C0392B',
  },
  mainActionButtonLeftClockIn: {
    backgroundColor: '#fff',
  },
  mainActionButtonTextLeftClockOut: {
    color: '#fff',
  },
});
